apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: loksai-eta-container
        image: devasishdas/sample
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  labels:
    app: sample
spec:
  selector:
    app: sample

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
